### ISSUE TITLE
unaligned pointer 0x2 when installed in  macpro

### ISSUE THREAD

**Issue by pianoboysai** [SevenBits/Enterprise#16]
I have a old macpro (early 2008), and efi version is 1.3. 
I tried Enterprise and Mac-Linux-USB-Loader,  the refind can detect USB successfully, but when I tried to boot, always got error:"unaligned pointer 0x2".

following is my tests:

Enterprise v0.2.1(or Mac-Linux-USB-Loader v2.0.1) + ubuntu-14.04-server-amd64 :
got error "unaligned pointer 0x2"

Enterprise v0.2.1(or Mac-Linux-USB-Loader v2.0.1) + ubuntu-14.04-server-amd64+mac : 
got error "unaligned pointer 0x2"

Enterprise v0.2.1(or Mac-Linux-USB-Loader v2.0.1) + ubuntu-14.10-server-amd64 :
got error "unaligned pointer 0x2"

Enterprise v0.2.1(or Mac-Linux-USB-Loader v2.0.1) + ubuntu-14.10-server-amd64, and add line "kernel /casper/vmlinuz.efi" : 
got error "unaligned pointer 0x2"

the only successful way is using Mac-Linux-USB-Loader v2.0.1 to download ubuntu-13.10 and install.

btw:
1.the boot.efi of Mac-Linux-USB-Loader v2.0.1 size is about 600K,  but boot.efi of Enterprise v0.2.1 is about 5MB, why so big difference?

2.according to the  Enterprise v0.2.1 document, ubuntu14.10 has been tested, but the document also said we need to use the Mac version ubuntu. 
as far as I know, ubuntu14.10 has no mac version, because it's not a LTS version. (14.04 is LTS)
, so this puzzles me.

could you help me for these questions? thanks!

**Comment by pokinoi** [comment]
Please someone HELP I have thesame problem. I am trying to install ubuntu on a macpro6,1  version 10.10.4 running OS X Yosemite. I am trying to install ubtuntu using reFind. The main issue is that when ever i boot EFI and try either the, try ubuntu or install ubuntu option, with or without nomodeset added, i get the following error message:

Booting a command list

error: file `/casper/vmlinuz.efi' not found
unaligned pointer 0xa5a5a5a5
Aborted. press any key to exit.

I would appreciate your support, if you can lend me ur skills on how to fix this. Thanks

**Comment by pokinoi** [comment]
Please someone HELP I have thesame problem. I am trying to install ubuntu on a macpro6,1  version 10.10.4 running OS X Yosemite. I am trying to install ubtuntu using reFind. The main issue is that when ever i boot EFI and try either the, try ubuntu or install ubuntu option, with or without nomodeset added, i get the following error message:

Booting a command list

error: file `/casper/vmlinuz.efi' not found
unaligned pointer 0xa5a5a5a5
Aborted. press any key to exit.

I would appreciate your support, if you can lend me ur skills on how to fix this. Thanks

**Comment by SevenBits** [comment]
@pokinoi What version of Mac Linux USB Loader did you use?

**Comment by pokinoi** [comment]
Thank you very much for your prompt reply, i am currently following, these instructions:

https://help.ubuntu.com/community/MacPro

The installation has been tested on Ubuntu Trusty Tahr - 14.04 using this version of reFind:
http://sourceforge.net/projects/refind/?source=typ_redirect

thanks

**Comment by pokinoi** [comment]
I am also thinking about having mac OS X on the mac with reFind installed and run ubuntu on a bootable USB stick.However, I am planning to use it to run salome and openFoam (parallel processing), i don't know if that is also possible?

thanks

**Comment by SevenBits** [comment]
I'm confused. The instructions on Ubuntu's site don't involve Mac Linux USB Loader at all. Those steps assume that you create an Ubuntu USB stick using Canonical's recommended method (which doesn't work well on Macs, IMHO). Are you using Mac Linux USB Loader as the installation media from which to boot the installer?

**Comment by pokinoi** [comment]
Hello, I have solved the problem and I can boot into ubuntu now using the try ubuntu option.I am also confused now. I think the ubuntu instructions involves using reFind, which is a mac linux boot loader am assuming. So yes. That been said, I simply just want to use the macpro to run salome and openfoam on ubuntu either running on internal hard drive or USB stick. I can see the option to create a start up disk, however, I don't have any Internet connection, I ve gone to system settings-additional drivers and have discovered broadcom...and checked to use it. But I still don't have any Internet connection.
