### ISSUE TITLE
Not starting: "Cant' set display mode! Unsupported"

### ISSUE THREAD

**Issue by ghost** [SevenBits/Enterprise#19]
Hello,

The boot procedure exits quite at the beginning due to "core files are missing". Because the displayed infos vanish quickly, I had to make a video from which I extracted attached screen shots (the procedure goes immediately on with booting normally OS X).

Config:
- MacBook Pro (13-inch, Early 2011
- Memory: 8GB
- Graphics: Intel HD Graphics 3000 512MB
- Software: OS X 10.9.5 (13F34)
- Boot ROM Version: MBP81.0047.B27
- SMC Version (system):	1.68f99

Mac Linux USB Loader:
- Version 3.0 (5092) / Note about checking for updates: it says "Loader 3.0 (8000) is now available... would you like to download it now?" > there is no way to get it. I always get the (5092) build.
- I tried various Distro: from within the app and by downloading directly from Ubuntu site. All versions (new and older ones) have the same problem. 

Note: I created the bootable USB stick on OS X on another system (an iMac) because the "MAC Linux USB Loader Version 3.0" did not work on the above MacBook Pro (after having selected the Distro in "Create Live USB", nothing happens. The app simply quits).

Many Thanks, jc

![screen shot 2014-12-28 at 14 36 27](https://cloud.githubusercontent.com/assets/10330746/5564029/94008f7c-8ea4-11e4-9e24-5629d1ffe745.png)

![screen shot 2014-12-28 at 14 35 39](https://cloud.githubusercontent.com/assets/10330746/5564032/9e377c6c-8ea4-11e4-868f-5bc93310d147.png)

**Comment by SevenBits** [comment]
The "can't set display mode" message should have been fixed in a recent commit, so I'm closing this issue now.
