### ISSUE TITLE
Problems with editing and copying .MLUL-Live-USB

### ISSUE THREAD

**Issue by efrecska** [SevenBits/Enterprise#20]
I have tried to change the .MLUL-Live-USB file (editing family and iso settings) after making a backup copy. At first I used Notepad, then Vim and gedit for Windows (I have set multiboot on my MBP). The result was boot failure every time. The boot up messages were too fast to be seen on my MBP. Finally, I copied back the original .MLUL-Live-USB file and it did not work any longer! Why? How to edit it under Windows? 
This is what I have tried: 

#This file is machine generated. Do not modify it unless you know what you are doing.

entry Ubuntu
family Ubuntu
iso Ubuntu_14.10.iso

entry Zorin
family Ubuntu
iso Zorin_9.1.iso

entry Boot Repair
family Ubuntu
iso Boot_Repair_Disk_14.11.iso

entry Debian
family Debian
iso Debian_gnome_7.5.0.iso

entry Elementary
family Ubuntu
iso Elementary_OS_Luna.iso

This was the original:
#This file is machine generated. Do not modify it unless you know what you are doing.

entry Ubuntu
family Ubuntu

**Comment by SevenBits** [comment]
One thing that's not clear from your message: is the error with Enterprise, or with booting the USB drive from Enterprise? You showed me your configuration file, but I'm still your sure exactly how you have everything set up.

Could you perhaps include screenshots or a video? Unless I know specifically what is wrong it is hard to help by doing anything other than taking shots in the dark.

**Comment by efrecska** [comment]
It was Enterprise booting error because one out of the five isos listed in MLUL was missing on the disk.
gVim for Windows works for editing.

I like so much that with your progam we can put multiple isos on the USB flash drive!
Another great feature! Like with Yumi.
BTW. Yumi needs iso files being continuous.
Is it the same for MLUSBL? 

Is there a way to remaster a Knoppix (or other Live Linux) ISO into an ISO working with MLUSBL?
As I can see with my entry level knowledge GRUB/UBUNTU ISOs are more compatible.

**Comment by efrecska** [comment]
It seems to me that one of the isos listed in MLUL must be named as 'boot.iso' on the disk. Otherwise Enterprise gives a 'no iso found' message. Correct?

**Comment by SevenBits** [comment]
@efrecska Yes, one of the ISO files must be named `boot.iso` in order for Enterprise to not return an error. This is left over from the earlier days before Enterprise supported booting multiple distributions, and I will eventually eliminate this requirement in future versions, as it is evidently no longer necessary.

Enterprise uses GRUB internally to load the actual ISO file, so it supports whatever ISO files GRUB supports. Yumi, I believe, actually expands the ISO files of some distributions, so maybe that is why the files need to be continuous.

It should be possible to re-master a Knoppix ISO file; I haven't tried it though. You should contact someone more familiar with Knoppix for help on this; perhaps [this site](http://ftp.knoppix.net/wiki/Knoppix_Remastering_Howto) will help?

Enterprise works best with ISO files containing distributions based on Ubuntu. They are easy to boot from ISOs, so they tend to work the best.

**Comment by efrecska** [comment]
Many thanks and continue this good work!
Ed

Date: Tue, 27 Jan 2015 10:18:56 -0800

**Comment by efrecska** [comment]
Hi!

I try to run MintyMac Mate and Tails 1.32 on my Macbook Pro (from 2011 - unsure what part of the year).
I get an error message "Unable to find a medium containing a live file system" with MintyMac Mate (and v1.2 as well),
and some sort of irq problem with Tails: "irq 11: nobody cared (try booting with the "irqpoll" option)" a several times, then "irq 11 disabled".

Changing Advanced Options did not make them running (choosing 1 and 2 makes MintyMac hanging at initramsf).

Perhaps my Macbook Pro version is not compatible with Tails?
Were you able running MintyMac at all?

The .MLUL-Live-USB file looks like this:

-----------------------------------------------------
#This file is machine generated. Do not modify it unless you know what you are doing.

entry MintyMac Mate
family Ubuntu
iso boot.iso

entry Tails 1.32
family Debian
iso Tails_1.32-32bit.iso
kernel /live/vmlinuz config live-media=removable findiso=/efi/boot/Tails_1.32-32bit.iso nopersistent noprompt timezone=Etc/UTC block.events_dfl_poll_msecs=1000 nox11autologin module=Tails noapic noapm nodma nomce nolapic nomodeset nosmp vga=normal irqpoll
-------------------------------------------------------

I greatly appreciate any help.

Sincerely yours,

Ede Frecska
