### ISSUE TITLE
boot.iso is needed

### ISSUE THREAD

**Issue by steve6375** [SevenBits/Enterprise#22]
I created a FAT32 USB stick under Windows and added Ubuntu.iso as \EFI\BOOT\boot.iso - it boots fine.
I then changed the boot.iso name to ubu.iso and changed the .MLUL-Live-USB entry
entry Ubuntu-14.10
family Ubuntu
iso ubu.iso

It did not work. I then added a new dummy file called \EFI\BOOT\boot.iso (size 0 bytes) - then it worked and I can choose Ubuntu-14-10 and boot OK.

Therefore, it seems that a boot.iso file MUST be present?

**Comment by SevenBits** [comment]
This is a regression from before Enterprise supported booting multiple distributions. It should be a relatively simple fix. Thanks for reporting.
