### ISSUE TITLE
Halts on utf8 is not a recommented IO charset line

### ISSUE THREAD

**Issue by DeadWelcome** [SevenBits/Enterprise#25]
Hey Sevenbits, 

Great work you are doing. I'm having trouble loading Tails from USB using Enterprise on 10.10 Mac Mini 2012, fallback bootloader. Used two USB sticks, latest was a 4GB. Splash screen does come up including Ent options and have tried turning off functions to run, also removing live-media=removable. It halts after:

**FAT-fs (sdb1): utf8 is not a recommented IO charset for FAT filesystems, filesystem will be case sensitive**

Seems to be a problem with mount? Both are formatted as FAT.

Using your latest build. This is a first time post.

Thanks

**Comment by SevenBits** [comment]
@DeadWelcome Could it be a problem with how you formatted the drive as FAT? How do you format the drive?

**Comment by DeadWelcome** [comment]
Only through Disk Utility following [these steps](http://www.hgst.com/support/faqs/how-format-my-drive-use-windows-and-mac-fat32). I haven't put any partitions on it and the USB is in slot one. My USB stick name always reverts to capital letters though, even tried **'bootme'** as the title. No avail. 

I feel like I'm so close!
