### ISSUE TITLE
Loading linux kernel fails on Macbook Pro,  Cannot find casper/vmlinuz.efi

### ISSUE THREAD

**Issue by jeremymodell** [SevenBits/Enterprise#26]
Using a Macbook Pro 15 mid 2010 10.10.3, and Mac Linux USB Loader v.3.0.2 and trying to load Linux Mint  17.1 Cinnamon edition, using Ubuntu settings. 

It seems  that the linux kernel won't load as once i boot into usb and try to boot into "Ubuntu", i get a brief error saying something along the lines of Kernel cannot  find Casper/vmlinuz.efi. A second error comes up after that saying it couldn't load the kernel. Then the grub screen comes up and it gives me an option to load into linux mint 17, but the screen will turn black once selected and eventually if you press the keyboard "/init line 7 can't open /dev/sdc no medium found" will repeat itself infinitely.

**Comment by jeremymodell** [comment]
Tried all the boot options. Nothing's worked thus far. 
If it helps this Macbook Pro has been customized to have 2 hard drives (the dvd drive has been replaced with one).

**Comment by SevenBits** [comment]
Please post your .MLUL-Live-USB file.

**Comment by jeremymodell** [comment]
It didn't create one automatically. Didn't know I had to generate one manually. Will try now with that. 

btw ubuntu 14.10 loaded fine.

**Comment by SevenBits** [comment]
I'll take a look at Mint 17.1 again.

**Comment by jeremymodell** [comment]
Just removing the file-=/cdrom/pressed/ubunut.seed part fixed the issue as a heads up.

**Comment by SevenBits** [comment]
@jeremymodell I suspect, then, that it was due to an error in how you configured Mac Linux USB Loader to set up your USB drive rather than an actual bug in the program.

**Comment by jeremymodell** [comment]
I only selected Family Ubuntu and Version older than 14.10, both of which are true. There's really only three options in the entire program, and I don't think I selected anything wrong. Maybe just add something to the documentation front page for Mac Linux USB Loader to make it clearer you have to tweak the .MLUL-Live-USB file?  It's just a bit confusing as it stands. The tool works great otherwise.

**Comment by napcs** [comment]
I have this issue with Ubuntu 12.04 LTS  64bit.  And the same solution applies.

The current 3.x build includes  =/cdrom/pressed/ubunut.seed  in my configuration file and the USB stick boots up a 2011 Macbook Air running Mavericks. 

It does not boot a 2014 Imac 21" running Yosemite.

Removing the line fixes the boot on the 2014 iMac *and* the 2011 Macbook Air.

To create the file I loaded the USB creator, chose the Ubuntu image, used the Enterprise source bundled with the app, did *not* choose the "this ISO lacks an EFI -enabled Kernel"  and *did* check the box for "This ISO has code older than Ubuntu 14.10". (These were the defaults presented to me.)

**Comment by leaded71** [comment]
Hi I am having similar problems. I am using the kali linux distro.  Here is my config file:
#This file is machine generated. Do not modify it unless you know what you are doing.

entry Kali
family Debian
kernel /live/vmlinuz findiso=/efi/boot/boot.iso boot=live noconfig=sudo username=root hostname=kali

entry Kali (installer)
family Debian
initrd /install/gtk/initrd.gz
kernel /install/gtk/vmlinuz findiso=/efi/boot/boot.iso boot=live noconfig=sudo username=root hostname=kali

The screen shots and errors I get are the following in sequence:

![2021-04-29 10 31 37](https://user-images.githubusercontent.com/9915282/116584468-003a6d80-a8dd-11eb-88cb-06c42465d243.jpg)
![2021-04-29 10 31 48](https://user-images.githubusercontent.com/9915282/116584487-04ff2180-a8dd-11eb-9c8b-63a6df5a77a3.jpg)
![2021-04-29 10 31 54](https://user-images.githubusercontent.com/9915282/116584494-06304e80-a8dd-11eb-9512-7dc398888804.jpg)
![2021-04-29 10 32 13](https://user-images.githubusercontent.com/9915282/116584500-07617b80-a8dd-11eb-89df-789001f15c96.jpg)
![2021-04-29 10 54 05](https://user-images.githubusercontent.com/9915282/116584505-092b3f00-a8dd-11eb-8922-5acdf178fe0c.jpg)
