### ISSUE TITLE
Extra characters are being passed in kernel path

### ISSUE THREAD

**Issue by YorikSar** [SevenBits/Enterprise#27]
I was trying to boot gentoo install CD iso. After writing it to USB stick with Mac-Linux-USB-Loader and fixing .MLUL-Live-USB to provide custom kernel/initrd paths (I've added `kernel /isolinux/gentoo root=/dev/ram0 <...>` and `initrd /isolinux/gentoo.igz` lines and removed `family Other` line, see [bug in Loader] (/SevenBits/Mac-Linux-USB-Loader/issue/68) ), I rebooted and found out that GRUB claims that it cant find `/isolinux/gentooptal?` for kernel. It seems Enterprise is passing extra characters to GRUB.

**Comment by SevenBits** [comment]
I've heard reports that this happens, but I've been unable to reproduce it consistently. Is it an encoding issue? Is there any chance that those characters are actually in your file?

**Comment by YorikSar** [comment]
I've already destroyed that file but can try to reproduce this. I've tried to move lines around, delete and rewrite these lines with no luck. I use Vim in en_US.UTF-8 locale for editing, so there's little chance some fancy Unicode symbol sneak in there. It looks very much like uninitialized memory usage for me...

**Comment by YorikSar** [comment]
I don't know exact semantics of [these methods] (https://github.com/SevenBits/Enterprise/blob/master/src/main.c#L284-L285) but from the looks of it I think not enough memory is allocated for `kernel_path` and so terminating zero byte is set in yet unallocated memory. After that somewhere another allocation happens and that zero gets overridden.

**Comment by SevenBits** [comment]
@YorikSar Internally the contents of the file are stored in a `CHAR8`, so a UTF-8 encoding should be okay.

It could be uninitialized memory, but the program generally works when additional parameters are passed. Though I have seen this bug before, I am unable to reproduce it consistently, and I don't want to prematurely start allocating more memory than needed, as I believe that UEFI imposes a cap on the system memory which you can use.

In terms of the behavior of the `AllocatePool` function, this is its behavior:

> The AllocatePool() function allocates a memory region of Size bytes from memory of type PoolType and returns the address of the allocated memory in the location referenced by Buffer. This function allocates pages from EfiConventionalMemory as needed to grow the requested pool type. All allocations are eight-byte aligned.

**Comment by YorikSar** [comment]
> All allocations are eight-byte aligned.

And that's why it works most of the time! I've checked: all "family" locations' lengths are not divisible by 8 . And `/isolinux/gentoo` is exactly 16 chars long. So you've been getting extra byte for terminating zero because of alignment.

I tried putting `/isolinux/gentoo1` there and it got parsed fine (didn't boot though, but that's because there's no such file), but `/isolinux/gentoo` steadily appears as `/isolinux/gentooptal?` on screen.

I don't know why all `AllocateMemoryAndCopyChar8String` work fine (probably some luck there too, without args kernel path is parsed fine), but that direct `AllocatePool` definitely needs extra byte.

**Comment by SevenBits** [comment]
@YorikSar You know what, I think you're right. I had never caught this before because I was unable to consistently reproduce the bug. I'll try it today and see if this happens, and if the alignment is the problem I'll fix it.

`AllocateMemoryAndCopyChar8String` is only different because it zeroes the memory after allocating it, though I'm sure that that will suffer the same issue as well at some point.
