### ISSUE TITLE
Linux Mint 17.1: Error: You need to load the kernel first

### ISSUE THREAD

**Issue by 007noon700** [SevenBits/Enterprise#29]
I moved this from the Mac-Linux-USB-Loader repo.

When I create a live USB and boot to the USB stick, all I get is "Error: You need to load the kernel first" then it sends me to GRUB. Am I missing something blindingly obvious to more experienced users? I haven't seen this issue much online and when I did, the solutions didn't seem to work.

**Comment by SevenBits** [comment]
What version of Mac Linux USB Loader are you using? And what distribution are you trying to load? Honestly, I need more information before I can say anything.

Also, these bug reports are not support forums. They are used to report *reproduceable issues* to me. Just an FYI for the future. :)

**Comment by 007noon700** [comment]
I'm using the latest version of Mac Linux USB Loader, 3.0.2 I believe. I'm
trying to install Linux Mint 17.1 Cinnamon. I'm using MacBook Pro 10,1
(mid-2012 retina) if that helps.

Sorry, I'll keep in mind that this is not support. Thanks for helping me
anyways!

**Comment by SevenBits** [comment]
@007noon700 Linux Mint works just fine with Mac Linux USB Loader. In order to get it to boot, you need to check the "Mac version of Ubuntu" checkbox on the installation options screen (for boring reasons which I won't get into here).

**Comment by 007noon700** [comment]
Well, I did that and now I'm getting an "attempt to read or write outside of disk 'loop'" error. Is this an issue with my flash drive?

**Comment by SevenBits** [comment]
@007noon700 Can you post your `.MLUL-Live-USB` file? I've never seen that error before.

**Comment by 007noon700** [comment]
Here is my .MLUL-Live-USB:
```
#This file is machine generated. Do not modify it unless you know what you are doing.

entry Ubuntu
family Ubuntu
kernel /casper/vmlinuz 
```

**Comment by SevenBits** [comment]
Hmm, that's odd. The file looks okay. Can you repeat the process with another USB stick?

**Comment by 007noon700** [comment]
Will do, I should be getting my other flash drive back soon.

**Comment by 007noon700** [comment]
I tried it with a different flash drive, it worked. Thanks for your help!

**Comment by SevenBits** [comment]
@007noon700 You're welcome!
