### ISSUE TITLE
error: invalid magic number with Mint 17.1 and MLUL 3.0.2

### ISSUE THREAD

**Issue by alexander-brett** [SevenBits/Enterprise#30]
Error occurs when trying to load the kernel. The partition is FAT32 and the drive has an MBR. I'm on a MacBook Pro (13-inch, Mid 2009).

Here's the .MLUL:

```
#This file is machine generated. Do not modify it unless you know what you are doing.

entry Ubuntu
family Ubuntu
kernel /casper/vmlinuz 
```

Cheers :)

**Comment by SevenBits** [comment]
Can you post a screenshot of the error? It's important that I see the actual error message.

**Comment by alexander-brett** [comment]
Not sure how to screenshot a grub error - literal photo?

**Comment by SevenBits** [comment]
That's the idea :)

**Comment by SevenBits** [comment]
@alexander-brett Unless you can provide more information, I'm going to close this thread. If this remains an issue, please re-open.

**Comment by dmitryfd** [comment]
I am getting the same issue with Kali Linux 2.0 (running on rMBP 13' Late 2013).
I was intially having the same issue as described [here](https://github.com/SevenBits/Mac-Linux-USB-Loader/issues/78), so I added an extra character to the kernel name in the config.

Now, the errors look something like this:
    Loading kernel... error: invalid magic number
    Loading RAM disk... error: error: you need to load the kernel first

I can provide you with a photo of that screen, if needed.
Any ideas how I could approach fixing it? Thanks in advance!

**Comment by SevenBits** [comment]
@dmitryfd Yes, please send a photo, and also post your Enterprise configuration file. Which version of Mac Linux USB Loader are you using?

**Comment by dmitryfd** [comment]
@SevenBits, I am using 3.1beta2.
Before I do that, someone online suggested that problem might actually be with a USB drive (bad sectors). I am trying right now with a different one and will report my findings.

**Comment by dmitryfd** [comment]
Nope, it's the same error, sadly :(

[Screenshot](http://imgur.com/ovQHQXg)
[Config file](http://pastebin.com/D0BiN5k6)

**Comment by SevenBits** [comment]
@dmitryfd Can you verify that your ISO isn't corrupted?

**Comment by dmitryfd** [comment]
@SevenBits It actually seems so. I was downloading the image via torrents and it seems like I am having SHA1SUM mismatch. I am redownloading and will try again tonight. Will update here if that solved it.

**Comment by dmitryfd** [comment]
Yup, redownloading the image actually fixed it.

Thanks for your time and sorry for troubling you!

**Comment by SevenBits** [comment]
@dmitryfd No problem, I'm glad you got it working! Feel free to donate if the program helped you.
