### ISSUE TITLE
pclinuxos does not boot

### ISSUE THREAD

**Issue by gilado** [SevenBits/Enterprise#31]
Trying to install pclinuxos www.pclinuxos.com on early 2015 Macbook Air.  
Created a USB with Mac Linux USB Loader.  

It seem to start correctly, fails to fully boot reporting "ERROR: Unable to mount the livecd"

In debug mode I see "DBG: I am after fromboot The LOOPMNT is"

(when booting an asus in debug mode you see "DBG: I am after fromboot The LOOPMNT is: 1")

I tried to create a USB for other OS and used both EFI aware and non EFI aware ISOs (community-kde64-pclinuxos-10.15.iso and pclinuxos-kde-2014.12.iso)

I also tried to create a USB for Ubuntu OS (indicating non EFI and older code) then replace boot.iso and edit enterprise.cfg

In enterprise.cfg I used

entry PCLOS
kernel /isolinux/vmlinuz livecd=livecd root=/dev/rd/3 vga=788 keyb=us
initrd /isolinux/initrd.gz

All fail the same way

More details here http://www.pclinuxos.com/forum/index.php/topic,134783.0.html

Could you please take a look?

**Comment by SevenBits** [comment]
@gilado Thanks, I'll do some investigating.
