### ISSUE TITLE
Kali linux hangs while booting

### ISSUE THREAD

**Issue by xtigerx** [SevenBits/Enterprise#32]
Hello,
After a few days, I've finally createda live usb of Kali that will be recognized and almost boot on my mid-2011 MacBook Pro. Actualli, it hangs at booting. 

![img_20151209_230949 1](https://cloud.githubusercontent.com/assets/16238253/11711949/56869280-9f2a-11e5-8ae1-2917c12e6163.jpg)

I tried booting in normal mode, using no nomodeset, but is still not working.

My enterprise.cfg file looks like:

>entry Kali
family Debian
kernel /live/vmlinuz boot=live noconfig=sudo username=root hostname=kali
initrd /live/initrd.img
root live

**Comment by SevenBits** [comment]
@xtigerx Try booting with `nomodeset`.

**Comment by xtigerx** [comment]
@SevenBits Thank you for your answer.

As I said before, I already tried with `nomodeset` and it doesn't work.

**Comment by SevenBits** [comment]
Apologies, you appeared to suggest in your email that you did not try nomodeset.

Does the screen ever go to black, or does it just hang on the screen you've shown?

**Comment by xtigerx** [comment]
Sorry it was a bad use of my english.

Actually it takes more than 10 min (at the beginning I thought that it was hanged) at `Assuming drive cache: write through` but after 10 min, it continues until `modprobe`.

It hangs there, the screen doesn't go to black.

I hope you can understand my english.

Thank you.

**Comment by SevenBits** [comment]
@xtigerx Without any further information, at this point it looks like it's a hardware problem. I would try to find a way to contact the folks at @offensive-security or at least file a bug. Let them know you're using Mac Linux USB Loader.
