### ISSUE TITLE
Building-Process Enterprise on CentOS 7 will not work

### ISSUE THREAD

**Issue by mawelo** [SevenBits/Enterprise#35]
build.sh and Makefile will not work on CentOS 7

Patches and documentation is included in file 
[Enterprise_ml_2016-03-15.ZIP](https://github.com/SevenBits/Enterprise/files/173816/Enterprise_ml_2016-03-15.ZIP)

**Comment by SevenBits** [comment]
@mawelo Hi there -- can you please fork this repository, make these changes on your end, and then submit a pull request? You can see how to do this in [the documentation](https://help.github.com/articles/fork-a-repo/).
