### ISSUE TITLE
Pentoo Support

### ISSUE THREAD

**Issue by Dygear** [SevenBits/Enterprise#39]
**Short Description of Problem:** Pentoo 2015.0 RC5 Support

**Expected Behavior:** 

Pentoo Linux Support

**Actual Behavior:** 

No Pentoo Linux Support

**Steps to Reproduce:** 
- [Download pentoo linux](https://www.pentoo.ch/download/) - I used Pentoo Linux 2015.0 RC5.
- Install onto USB Drive using [Mac Linux USB Loader](https://blog.sevenbits.tk/Mac-Linux-USB-Loader/).
- Configure the `enterprise.cfg` file.
  
  entry Custom Linux
  kernel /efi/boot/boot.efi
  initrd /efi/boot/boot.iso

The actual values are unknown to me. This was my best guess and that simply does not work.

**Comment by SevenBits** [comment]
> The actual values are unknown to me. This was my best guess and that simply does not work.

What have you done to try to find the correct values?
