### ISSUE TITLE
Won't Compile Under OS X

### ISSUE THREAD

**Issue by evilninjection** [SevenBits/Enterprise#4]
After installing osxbook (http://osxbook.com/book/bonus/chapter4/efiprogramming/) to satisfy Enterprise's dependencies (install-deps.sh wouldn't work) running build.sh under gcc (I ran `export CC=gcc`) resulted in these errors:

main.c: In function ‘efi_main’:
main.c:75: warning: unused variable ‘result’
utils.c: In function ‘FileExists’:
utils.c:183: warning: passing argument 5 of ‘dir->Open’ makes integer from pointer without a cast
utils.c: In function ‘FileRead’:
utils.c:205: warning: passing argument 3 of ‘dir->Open’ discards qualifiers from pointer target type
utils.c:205: warning: passing argument 5 of ‘dir->Open’ makes integer from pointer without a cast
ld: unknown option: -nostdlib
make: **\* [enterprise.so] Error 1
mv: rename src/enterprise.efi to bin/enterprise.efi: No such file or directory
rm: _.so: No such file or directory
make: *_\* [clean] Error 1
./build.sh: line 27: return: can only `return' from a function or sourced script

I'm not sure if compiling Enterprise with OS X is something you plan on supporting but currently, there does not appear to be an easy way to compile under OS X.

Computer and program information:

Darwin Stevens-MacBook.local 11.4.2 Darwin Kernel Version 11.4.2: Thu Aug 23 16:26:45 PDT 2012; root:xnu-1699.32.7~1/RELEASE_I386 i386

Using built-in specs.
Target: i686-apple-darwin11
Configured with: /private/var/tmp/llvmgcc42/llvmgcc42-2336.11~67/src/configure --disable-checking --enable-werror --prefix=/Applications/Xcode.app/Contents/Developer/usr/llvm-gcc-4.2 --mandir=/share/man --enable-languages=c,objc,c++,obj-c++ --program-prefix=llvm- --program-transform-name=/^[cg][^.-]*$/s/$/-4.2/ --with-slibdir=/usr/lib --build=i686-apple-darwin11 --enable-llvm=/private/var/tmp/llvmgcc42/llvmgcc42-2336.11~67/dst-llvmCore/Developer/usr/local --program-prefix=i686-apple-darwin11- --host=x86_64-apple-darwin11 --target=i686-apple-darwin11 --with-gxx-include-dir=/usr/include/c++/4.2.1
Thread model: posix
gcc version 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)

**Comment by SevenBits** [comment]
Since commit [e2010e7](
https://github.com/SevenBits/Enterprise/commit/e2010e72e91cbdf76d609fb899d184001b95b84c), it is now finally possible to compile Enterprise on OS X.
