### ISSUE TITLE
Cant boot Kali Linux(kali-linux-2016.1-amd64.iso) from usb on late 2011 macbook pro using Mac Linux USB Loader 3.3(stable)

### ISSUE THREAD

**Issue by brandplysreese** [SevenBits/Enterprise#41]
**Short Description of Problem:** 
Cant boot Kali Linux(kali-linux-2016.1-amd64.iso) from usb on late 2011 macbook pro(osx 10.11.4) using Mac Linux USB Loader 3.3(stable)

I downloaded the kali iso and verified the SHA1Sum.
I formatted the usb FAT and successfully loaded the iso on the usb via Mac Linux USB Loader 3.3.

Once I reboot I can select the usb with kali in the reFind menu and get the Enterprise options. I choose to boot linux from the iso file and select Kali via the options. The system appears to start booting and then freezes.

**Expected Behavior:** 

Boot Kali Linux in live mode from a usb created with Mac Linux USB Loader 3.3.

**Actual Behavior:** 

After  "attempting to load the linux distribution now" message in enterprise, it tries to load kali and freezes after a few seconds.

**Steps to Reproduce:** 

I downloaded the kali iso and verified the SHA1Sum.
I formatted the usb FAT and successfully loaded the iso on the usb via Mac Linux USB Loader 3.3.

Once I reboot I can select the usb with kali in the reFind menu and get the Enterprise options. I choose to boot linux from the iso file and select Kali via the options. The system appears to start booting and then freezes.

*Note:* I have tried all the options from the enterprise advanced menu for kali. I have also tried to use MLUL with tails and ubuntu with similar problems

Attached are links to gifs and screen shots.

http://imgur.com/uWzoTw6
http://imgur.com/RPZvA61

![photo aug 22 3 11 41 pm](https://cloud.githubusercontent.com/assets/12085564/17869492/7e26f30e-6881-11e6-896c-7cc91ea96aba.jpg)
![photo aug 22 3 11 56 pm](https://cloud.githubusercontent.com/assets/12085564/17869491/7e256b74-6881-11e6-9f5a-d43378194dd4.jpg)

![screen shot 2016-08-22 at 3 37 06 pm](https://cloud.githubusercontent.com/assets/12085564/17871827/4333dffa-688b-11e6-9ff3-65852e304992.png)

**Comment by SevenBits** [comment]
Try enabling `nomodeset`, as described in [the documentation](https://github.com/SevenBits/Mac-Linux-USB-Loader/wiki/What-To-Do-if-Things-Don't-Work#the-usb-boots-on-my-mac-but-i-dont-have-graphics-or-i-get-a-black-screen).

**Comment by brandplysreese** [comment]
Thank you for the reply. I have tried with nomodeset enabled and got the same results. 

"Note: I have tried all the options from the enterprise advanced menu for kali"

![img_1837](https://cloud.githubusercontent.com/assets/12085564/17872332/8eaa212c-688d-11e6-9768-8732bba85869.JPG)
![img_1842](https://cloud.githubusercontent.com/assets/12085564/17872337/97e7b6c8-688d-11e6-9703-ef4564c5799a.JPG)
![img_1840](https://cloud.githubusercontent.com/assets/12085564/17872338/9b2c1ae0-688d-11e6-99c6-a5cc13862471.JPG)

If I wait about five minutes the screen goes dark and powers off.

**Comment by SevenBits** [comment]
@brandplysreese Due to a bug in the Enterprise boot loader in 3.3, `nomodeset` is not actually enabled properly. The patch will be rolled out soon. In the meantime, please add the `nomodeset` option to the Enterprise configuration file (you can find the option to edit it in the Setup USB Device screen of Mac Linux USB Loader).

**Comment by brandplysreese** [comment]
Is this the correct way to add the option to the enterprise config?

![screen shot 2016-08-22 at 7 06 12 pm](https://cloud.githubusercontent.com/assets/12085564/17874736/97f18758-689b-11e6-82af-a02a01f2fb45.png)

**Comment by SevenBits** [comment]
Yes.

**Comment by brandplysreese** [comment]
Thanks again for the response. Adding the nomodeset option gave  me the same results as above. Still freezes when trying to boot.

![img_1845](https://cloud.githubusercontent.com/assets/12085564/17899973/3d1243fa-692b-11e6-97a0-bfc665e02314.JPG)

**Comment by SevenBits** [comment]
@brandplysreese Try moving `nomodeset` to the end of the kernel parameters line, I always have it there and that might have something to do with it.

Other than that, I don’t know. It’s probably a hardware/driver issue. I’d file a bug report with a Kali developers; the OS has booted, so it’s their code running from here on out.

**Comment by brandplysreese** [comment]
Moving the option to the end yielded the same results. thanks for trying to help.

**Comment by SevenBits** [comment]
@brandplysreese No problem. Let me know what the Kali developers say.
