### ISSUE TITLE
Question regarding custom kernels

### ISSUE THREAD

**Issue by PanosSakkos** [SevenBits/Enterprise#43]
Hi,

The [contact](http://blog.sevenbits.io/contact.html) page is broken, so I'll ask my question here :smile:

Is it possible to specify a kernel and an initrd that are not part of the iso file?

Thanks for the great work!
:panos

**Comment by SevenBits** [comment]
> Is it possible to specify a kernel and an initrd that are not part of the iso file?

Not at this time. The kernel must be present within the ISO file. There is a possibility this may change in the future.
