### ISSUE TITLE
A black screen appears after i dual booted kali linux on mac

### ISSUE THREAD

**Issue by amit0j** [SevenBits/Enterprise#44]
Hi I dual booted kali linux on my imac it seemed to go well but as soon as i get the option to boot into kali linux my keyboard doesn't work and it goes to the black screen some code appears that says fail and then it says recovering journal and then the screen goes black.
Please any help would be really appreciated.

-amitoj.

**Comment by SevenBits** [comment]
What model of Mac are you using?

**Comment by amit0j** [comment]
Its an imac 2011

**Comment by SevenBits** [comment]
@amit0j Have you tried botting with the `nomodeset` option, available in the Advanced Boot Options menu?

**Comment by amit0j** [comment]
Actually I was just starting with coding after a few tutorial i dont know how to get to the advanced options i can see advanced options for kali GNU/Linux option but in that option there are only two other option which are normal boot and recovery mode and both won't do anything. I can acces a command line by pressing 'c' thats it.

**Comment by amit0j** [comment]
I am not even able to boot into macOS it straight away boots into the kali menu. I have uploaded some screenshots-
www.ibb.com/fU8Chk
www.ibb.co/bFMMa5
www.ibb.co/gYGtoQ

**Comment by SevenBits** [comment]
Hi Amit, your second screenshot shows the native Kali Linux boot menu. Ordinarily this does not appear when you use Mac Linux USB Loader. Were your USB drives created with Mac Linux USB Loader?

**Comment by amit0j** [comment]
No I didn't use mac linux usb loader i used a third party application it was called bootable usb maker. If i can just boot into macOS i can repeat the process?

**Comment by SevenBits** [comment]
I can't provide support for tools that are not my own. If you use Mac Linux USB Loader, then I can help you.
