### ISSUE TITLE
Macbook Pro, Ubuntu 18.04.1, Load linux kernel... error: file '/casper/vmlinuz.efi not found'

### ISSUE THREAD

**Issue by dave-k** [SevenBits/Enterprise#48]
**Short Description of Problem:** 

Loading linux kernel fails on Macbook Pro, error: file '/casper/vmlinuz.efi not found' 
This is similar to this [issue](https://github.com/SevenBits/Enterprise/issues/26) but using ubuntu-18.04.1 instead of Linux Mint 17.1

    MacBook Pro (Retina, 15-inch, Mid 2015)
    macOS High Sierra version 10.13.6
    Mac Linux USB Loader v.3.4.6 (9693)
    ubuntu-18.04.1-desktop-amd64.iso.

**Expected Behavior:** 

    Expected ubuntu to boot from USB

<img width="1163" alt="screen shot 2018-12-10 at 11 14 30 am" src="https://user-images.githubusercontent.com/5447484/49755125-e1d06a80-fc6c-11e8-9422-56d7b67df2ab.png">

**Actual Behavior:** 

    Error messages
    Load linux kernel... error: file '/casper/vmlinuz.efi not found'
    Loading initial RAM disk... error: you need to load the kernel first

![20181210_102531](https://user-images.githubusercontent.com/5447484/49752857-784d5d80-fc66-11e8-971e-c37b40098081.jpg)

**Steps to Reproduce:** 

Follow the USB loader instructions to create Ubuntu USB stick

**Comment by dave-k** [comment]
Is there any help or suggestions how to get past the error?

    file '/casper/vmlinuz.efi not found'

Here are 2 more screen shots which show that, even though

     The following distributions have been detected on this USB

selecting Ubuntu generates an error: 

    Load linux kernel... error: file '/casper/vmlinuz.efi not found'

![20181211_225415](https://user-images.githubusercontent.com/5447484/49852663-9ff11280-fd99-11e8-9851-3346695b22e5.jpg)

    1) Boot Linux from ISO file

![20181211_225530](https://user-images.githubusercontent.com/5447484/49852714-c0b96800-fd99-11e8-9f73-93648667a26f.jpg)

    1) Ubuntu

    See previous post
    Error messages
    Load linux kernel... error: file '/casper/vmlinuz.efi not found'
    Loading initial RAM disk... error: you need to load the kernel first

**Comment by SevenBits** [comment]
Hi @dave-k, could you try removing the ‘.efi’ from the end of the kernel name?

**Comment by dave-k** [comment]
Hi @sevenbits, "removing the ‘.efi’ from the end of the kernel name" was successful. 
Ubuntu is now up and running from the USB stick. Thanks

**Comment by SevenBits** [comment]
@dave-k, you’re welcome!
